SectionVerb {
    EnableSequence [
        cset "name='QUAT_MI2S_RX Audio Mixer MultiMedia1' 1"
    ]

    DisableSequence [
        cset "name='QUAT_MI2S_RX Audio Mixer MultiMedia1' 0"
    ]

    Value {
        TQ "HiFi"
    }
}

SectionDevice."Speaker" {
    Comment "Built-in speaker"

    EnableSequence [
        cset "name='Configuration' 4"
        cset "name='TAS2559 DAC Playback Volume' 12"
    ]

    Value {
        PlaybackPriority 100
        PlaybackPCM "hw:${CardId},0"
    }
}
